- hosts: localhost
  connection: local
  become: no
  become_user: root
  tasks:
    - name: "Simulate connection failure"
      lineinfile:
        path: ~/ansible-working/error-handling/report.yml
        regex: "url:."
        line:  '            url: https://bit.ly/3dtJtR8'
      tags:
      - service_down

    - name: "Restore service"
      lineinfile:
        path: ~/ansible-working/error-handling/report.yml
        regex: "url:."
        line:  '            url: https://bit.ly/3dtJtR7'
      tags:
      - service_up
